apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "production-reliability-api"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "production-reliability-api.default.svc.cluster.local:8000"
